# Generated by Django 5.2.17 on 2026-08-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmirecord',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
